[package]
name = "mini-pascal-compiler"
version = "0.1.0"
authors = ["Vili Lipo <vili.lipo@helsinki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
